Remove nami-utils usage from blacksmith-extra-component-types
bitnami/blacksmith-extra-component-types pull request #82
Opened 2022-01-17 12:12 UTC by marcosbc

Removes any usage of nami-utils in the blacksmith-extra-component-types repo.

NOTE: fs-extra is added temporarily until Blacksmith is updated to Node.js 16.x or higher.

2022-01-17 16:08 UTC, javsalgar commented on go-project/index.js
> +      'curl', ['-L', 'https://golang.org/VERSION?m=text'], {encoding: 'utf8'}
Could you explain the need of the encoding?

2022-01-17 16:10 UTC, marcosbc commented on go-project/index.js
> +      'curl', ['-L', 'https://golang.org/VERSION?m=text'], {encoding: 'utf8'}
`child.spawnSync` has a default encoding of `stream`, so that if you don't set `utf8`, the `stdout`/`stderr` output object will be a stream and not a string.

2022-01-17 16:12 UTC, javsalgar commented on go-project/index.js
> +      throw new Error('Failed to execute curl');
I think we should provide a bit more debugging information. Right now in Blacksmith we could see why it failed. We should show. Maybe just doing a JSON.stringify of the returned object should be enough.

```
{
  error: Error: spawnSync incorrect_command ENOENT
      at Object.spawnSync (internal/child_process.js:1067:20)
      at Object.spawnSync (child_process.js:602:24)
      at REPL12:1:19
      at Script.runInThisContext (vm.js:133:18)
      at REPLServer.defaultEval (repl.js:484:29)
      at bound (domain.js:413:15)
      at REPLServer.runBound [as eval] (domain.js:424:12)
      at REPLServer.onLine (repl.js:817:10)
      at REPLServer.emit (events.js:327:22)
      at REPLServer.EventEmitter.emit (domain.js:467:12) {
    errno: -2,
    code: 'ENOENT',
    syscall: 'spawnSync incorrect_command',
    path: 'incorrect_command',
    spawnargs: []
  },
  status: null,
  signal: null,
  output: null,
  pid: 4481,
  stdout: null,
  stderr: null
}
```

2022-01-17 16:15 UTC, javsalgar commented on go-project/index.js
> +      'curl', ['-L', 'https://golang.org/VERSION?m=text'], {encoding: 'utf8'}
Ok!

2022-01-17 16:15 UTC, javsalgar commented on go-project/index.js
> +      'curl', ['-L', 'https://golang.org/VERSION?m=text'], {encoding: 'utf8'}
Resolved

2022-01-17 16:38 UTC, javsalgar requested changes
Awesome work! Some changes requested

2022-01-17 16:38 UTC, javsalgar commented on node-application/index.js
>          _.flatten(['install', _additionalModules, '--save']), {cwd: this.prefix});
Maybe we can use `flat()` so we can get rid of lodash (one less package so less security issues)

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/flat

2022-01-17 16:38 UTC, javsalgar commented on pecl-component/index.js
> +    fse.removeSync(path.join(this.prefix, 'lib/php/extensions/no-debug-non-zts-*'));
Did you check that patterns work in removeSync?

```
 /tmp/testo                                                                       17:23:11  jsalmeron
❯ touch example1
 /tmp/testo                                                                       17:23:18  jsalmeron
❯ touch example2
 /tmp/testo                                                                       17:23:20  jsalmeron
❯ node
Welcome to Node.js v14.15.5.
Type ".help" for more information.
> fse = require('fs-extra')
{
  appendFile: [Function: appendFile],
  appendFileSync: [Function: appendFileSync],
  access: [Function: access],
  accessSync: [Function: accessSync],
  chown: [Function (anonymous)],
  chownSync: [Function (anonymous)],
  chmod: [Function (anonymous)],
  chmodSync: [Function (anonymous)],
  close: [Function: close],
  closeSync: [Function: closeSync],
  copyFile: [Function: copyFile],
  copyFileSync: [Function: copyFileSync],
  createReadStream: [Function: createReadStream],
  createWriteStream: [Function: createWriteStream],
  exists: [Function (anonymous)],
  existsSync: [Function: existsSync],
  fchown: [Function (anonymous)],
  fchownSync: [Function (anonymous)],
  fchmod: [Function (anonymous)],
  fchmodSync: [Function (anonymous)],
  fdatasync: [Function: fdatasync],
  fdatasyncSync: [Function: fdatasyncSync],
  fstat: [Function (anonymous)],
  fstatSync: [Function (anonymous)],
  fsync: [Function: fsync],
  fsyncSync: [Function: fsyncSync],
  ftruncate: [Function: ftruncate],
  ftruncateSync: [Function: ftruncateSync],
  futimes: [Function: futimes],
  futimesSync: [Function: futimesSync],
  lchown: [Function (anonymous)],
  lchownSync: [Function (anonymous)],
  lchmod: [Function (anonymous)],
  lchmodSync: [Function (anonymous)],
  link: [Function: link],
  linkSync: [Function: linkSync],
  lstat: [Function (anonymous)],
  lstatSync: [Function (anonymous)],
  lutimes: [Function: lutimes],
  lutimesSync: [Function: lutimesSync],
  mkdir: [Function: mkdir],
  mkdirSync: [Function: mkdirSync],
  mkdtemp: [Function: mkdtemp],
  mkdtempSync: [Function: mkdtempSync],
  open: [Function: open],
  openSync: [Function: openSync],
  opendir: [Function: opendir],
  opendirSync: [Function: opendirSync],
  readdir: [Function: readdir],
  readdirSync: [Function: readdirSync],
  read: [Function (anonymous)],
  readSync: [Function (anonymous)],
  readv: [Function: readv],
  readvSync: [Function: readvSync],
  readFile: [Function: readFile],
  readFileSync: [Function: readFileSync],
  readlink: [Function: readlink],
  readlinkSync: [Function: readlinkSync],
  realpath: [Function: realpath] { native: [Function (anonymous)] },
  realpathSync: [Function: realpathSync] { native: [Function (anonymous)] },
  rename: [Function: rename],
  renameSync: [Function: renameSync],
  rm: [Function: rm],
  rmSync: [Function: rmSync],
  rmdir: [Function: rmdir],
  rmdirSync: [Function: rmdirSync],
  stat: [Function (anonymous)],
  statSync: [Function (anonymous)],
  symlink: [Function: symlink],
  symlinkSync: [Function: symlinkSync],
  truncate: [Function: truncate],
  truncateSync: [Function: truncateSync],
  unwatchFile: [Function: unwatchFile],
  unlink: [Function: unlink],
  unlinkSync: [Function: unlinkSync],
  utimes: [Function: utimes],
  utimesSync: [Function: utimesSync],
  watch: [Function: watch],
  watchFile: [Function: watchFile],
  writeFile: [Function: writeFile],
  writeFileSync: [Function: writeFileSync],
  write: [Function (anonymous)],
  writeSync: [Function: writeSync],
  writev: [Function (anonymous)],
  writevSync: [Function: writevSync],
  Dir: [class Dir],
  Dirent: [class Dirent],
  Stats: [Function: Stats],
  ReadStream: [Function: ReadStream],
  WriteStream: [Function: WriteStream],
  FileReadStream: [Function: ReadStream],
  FileWriteStream: [Function: WriteStream],
  _toUnixTimestamp: [Function: toUnixTimestamp],
  F_OK: 0,
  R_OK: 4,
  W_OK: 2,
  X_OK: 1,
  constants: [Object: null prototype] {
    UV_FS_SYMLINK_DIR: 1,
    UV_FS_SYMLINK_JUNCTION: 2,
    O_RDONLY: 0,
    O_WRONLY: 1,
    O_RDWR: 2,
    UV_DIRENT_UNKNOWN: 0,
    UV_DIRENT_FILE: 1,
    UV_DIRENT_DIR: 2,
    UV_DIRENT_LINK: 3,
    UV_DIRENT_FIFO: 4,
    UV_DIRENT_SOCKET: 5,
    UV_DIRENT_CHAR: 6,
    UV_DIRENT_BLOCK: 7,
    S_IFMT: 61440,
    S_IFREG: 32768,
    S_IFDIR: 16384,
    S_IFCHR: 8192,
    S_IFBLK: 24576,
    S_IFIFO: 4096,
    S_IFLNK: 40960,
    S_IFSOCK: 49152,
    O_CREAT: 512,
    O_EXCL: 2048,
    UV_FS_O_FILEMAP: 0,
    O_NOCTTY: 131072,
    O_TRUNC: 1024,
    O_APPEND: 8,
    O_DIRECTORY: 1048576,
    O_NOFOLLOW: 256,
    O_SYNC: 128,
    O_DSYNC: 4194304,
    O_SYMLINK: 2097152,
    O_NONBLOCK: 4,
    S_IRWXU: 448,
    S_IRUSR: 256,
    S_IWUSR: 128,
    S_IXUSR: 64,
    S_IRWXG: 56,
    S_IRGRP: 32,
    S_IWGRP: 16,
    S_IXGRP: 8,
    S_IRWXO: 7,
    S_IROTH: 4,
    S_IWOTH: 2,
    S_IXOTH: 1,
    F_OK: 0,
    R_OK: 4,
    W_OK: 2,
    X_OK: 1,
    UV_FS_COPYFILE_EXCL: 1,
    COPYFILE_EXCL: 1,
    UV_FS_COPYFILE_FICLONE: 2,
    COPYFILE_FICLONE: 2,
    UV_FS_COPYFILE_FICLONE_FORCE: 4,
    COPYFILE_FICLONE_FORCE: 4
  },
  promises: {
    access: [AsyncFunction: access],
    copyFile: [AsyncFunction: copyFile],
    open: [AsyncFunction: open],
    opendir: [Function: opendir],
    rename: [AsyncFunction: rename],
    truncate: [AsyncFunction: truncate],
    rm: [AsyncFunction: rm],
    rmdir: [AsyncFunction: rmdir],
    mkdir: [AsyncFunction: mkdir],
    readdir: [AsyncFunction: readdir],
    readlink: [AsyncFunction: readlink],
    symlink: [AsyncFunction: symlink],
    lstat: [AsyncFunction: lstat],
    stat: [AsyncFunction: stat],
    link: [AsyncFunction: link],
    unlink: [AsyncFunction: unlink],
    chmod: [AsyncFunction: chmod],
    lchmod: [AsyncFunction: lchmod],
    lchown: [AsyncFunction: lchown],
    chown: [AsyncFunction: chown],
    utimes: [AsyncFunction: utimes],
    lutimes: [AsyncFunction: lutimes],
    realpath: [AsyncFunction: realpath],
    mkdtemp: [AsyncFunction: mkdtemp],
    writeFile: [AsyncFunction: writeFile],
    appendFile: [AsyncFunction: appendFile],
    readFile: [AsyncFunction: readFile]
  },
  gracefulify: [Function: patch],
  copySync: [Function: copySync],
  copy: [Function: copy],
  emptyDirSync: [Function: emptyDirSync],
  emptydirSync: [Function: emptyDirSync],
  emptyDir: [Function: emptyDir],
  emptydir: [Function: emptyDir],
  createFile: [Function: createFile],
  createFileSync: [Function: createFileSync],
  ensureFile: [Function: createFile],
  ensureFileSync: [Function: createFileSync],
  createLink: [Function: createLink],
  createLinkSync: [Function: createLinkSync],
  ensureLink: [Function: createLink],
  ensureLinkSync: [Function: createLinkSync],
  createSymlink: [Function: createSymlink],
  createSymlinkSync: [Function: createSymlinkSync],
  ensureSymlink: [Function: createSymlink],
  ensureSymlinkSync: [Function: createSymlinkSync],
  readJson: [Function: _readFile],
  readJsonSync: [Function: readFileSync],
  writeJson: [Function: _writeFile],
  writeJsonSync: [Function: writeFileSync],
  outputJson: [Function: outputJson],
  outputJsonSync: [Function: outputJsonSync],
  outputJSON: [Function: outputJson],
  outputJSONSync: [Function: outputJsonSync],
  writeJSON: [Function: _writeFile],
  writeJSONSync: [Function: writeFileSync],
  readJSON: [Function: _readFile],
  readJSONSync: [Function: readFileSync],
  mkdirs: [Function (anonymous)],
  mkdirsSync: [Function (anonymous)],
  mkdirp: [Function (anonymous)],
  mkdirpSync: [Function (anonymous)],
  ensureDir: [Function (anonymous)],
  ensureDirSync: [Function (anonymous)],
  moveSync: [Function: moveSync],
  move: [Function: move],
  outputFile: [Function: outputFile],
  outputFileSync: [Function: outputFileSync],
  pathExists: [Function: pathExists],
  pathExistsSync: [Function: existsSync],
  remove: [Function: remove],
  removeSync: [Function: removeSync]
}
> fse.removeSync('example*');
undefined
>
 /tmp/testo                                                 [...]

2022-01-17 16:38 UTC, javsalgar commented on ruby-application/index.js
>      _.forEach(['darwin*', 'freebsd*', 'openbsd*', 'linux-i686', 'linux/i686'], value => {
Let's change it to vanilla forEach so we can get rid of lodash

2022-01-17 16:38 UTC, javsalgar commented on ruby-application/index.js
> +    fse.removeSync(path.join(this.prefix, 'log/*'));
Check that this works, in my tests it didn't

2022-01-17 16:38 UTC, javsalgar commented on package.json
> +  "version": "0.0.74",
I think we should get rid of this nonsense versioning we're using.

2022-01-17 16:38 UTC, javsalgar commented on package.json
>      "lodash": "^4.17.21",
Ideally, getting rid of lodash would be awesome to avoid more security issues. The less we have the better.

2022-01-17 16:38 UTC, javsalgar commented on package.json
>      "eslint-plugin-import": "^2.17.2",
Maybe checking these devDepedencies would make sense, we would avoid the dependabot to continuously complaining on security issues

2022-01-17 16:39 UTC, marcosbc commented on go-project/index.js
> +      throw new Error('Failed to execute curl');
ok, changed

2022-01-17 16:40 UTC, marcosbc commented on package.json
>      "lodash": "^4.17.21",
That is currently something out of scope for this project, it would require a lot of changes as well, and fortunately there is someone maintaining it (unlike `nami-utils`).

2022-01-17 16:40 UTC, marcosbc commented on package.json
> +  "version": "0.0.74",
What are you suggesting? For now I don't want to introduce breaking changes.

2022-01-17 16:43 UTC, marcosbc commented on ruby-application/index.js
> +    fse.removeSync(path.join(this.prefix, 'log/*'));
You sure? It worked for me. 

```
$ mkdir foo
$ touch foo/bar
```

and then in the Node.js console:

```
const fse = require('fs-extra');
fse.removeSync('foo/*')
```

Afterwards you can see that the `foo` folder is empty.

2022-01-17 16:44 UTC, marcosbc commented on package.json
>      "eslint-plugin-import": "^2.17.2",
Yep, but that is something I would like to do later. Right now the urgency is in getting it removed from `blacksmith-extra-component-types` so we can continue working on the removal from `blacksmith`.

2022-01-17 16:45 UTC, marcosbc commented on ruby-application/index.js
>      _.forEach(['darwin*', 'freebsd*', 'openbsd*', 'linux-i686', 'linux/i686'], value => {
Let's do that later

2022-01-17 16:45 UTC, marcosbc commented on pecl-component/index.js
> +    fse.removeSync(path.join(this.prefix, 'lib/php/extensions/no-debug-non-zts-*'));
You sure? It worked for me. 

```
$ mkdir foo
$ touch foo/bar
```

and then in the Node.js console:

```
const fse = require('fs-extra');
fse.removeSync('foo/*')
```

Afterwards you can see that the `foo` folder is empty.

2022-01-17 16:47 UTC, marcosbc commented on node-application/index.js
>          _.flatten(['install', _additionalModules, '--save']), {cwd: this.prefix});
I'm mentioning this above, but removing lodash is not trivial and I would like to do that at a later stage, but with much less priority since it is a well-maintained package.

2022-01-17 17:20 UTC, marcosbc commented on node-application/index.js
>          _.flatten(['install', _additionalModules, '--save']), {cwd: this.prefix});
@javsalgar `flat()` is not supported in Node.js 8.x nor 10.x. Unfortunately removing lodash at this moment is not feasible until we upgrade the Node.js runtime requirement for Blacksmith.

2022-01-21 16:48 UTC, marcosbc commented on node-application/index.js
>          _.flatten(['install', _additionalModules, '--save']), {cwd: this.prefix});
Let's leave the lodash removal to later

2022-01-21 16:50 UTC, marcosbc commented on ruby-application/index.js
>      _.forEach(['darwin*', 'freebsd*', 'openbsd*', 'linux-i686', 'linux/i686'], value => {
We are discussing lodash removal above, so I'll close this conversation.

2022-01-21 16:50 UTC, marcosbc commented on package.json
> +  "version": "0.0.74",
For now I'd not change this. We can change the versioning approach later on.

2022-01-21 16:51 UTC, marcosbc commented on package.json
>      "eslint-plugin-import": "^2.17.2",
This is something we will do later on, in order to unblock the nami-utils removal.

2022-01-21 17:35 UTC, marcosbc commented on node-application/index.js
>          _.flatten(['install', _additionalModules, '--save']), {cwd: this.prefix});
I've replaced all lodash occurrences except for `_.flat`, until I fix Gulp usage in this repo with Node.js 16.x.

2022-01-21 17:35 UTC, marcosbc commented on ruby-application/index.js
> +    fse.removeSync(path.join(this.prefix, 'log/*'));
Let's continue in the other discussion.

2022-01-21 18:32 UTC, marcosbc commented on node-application/index.js
>          _.flatten(['install', _additionalModules, '--save']), {cwd: this.prefix});
I've replaced all lodash usage with native Node.js code

2022-01-21 18:55 UTC, marcosbc commented on pecl-component/index.js
> +    fse.removeSync(path.join(this.prefix, 'lib/php/extensions/no-debug-non-zts-*'));
Fixed

2022-01-24 10:30 UTC, javsalgar commented on test/drupal-plugin.js
> +  beforeEach('prepare environment', function() {
Why changing the ES6 syntax with the old syntax?

2022-01-24 10:51 UTC, marcosbc commented on test/drupal-plugin.js
> +  beforeEach('prepare environment', function() {
This is due to the `plugin:mocha/recommended` linter rules. This was changed automatically with `eslint --fix`.

2022-01-24 10:57 UTC, javsalgar approved these changes

2022-01-24 11:17 UTC, merged